-- ==========================================================================
-- Rounds — Supabase schema
-- ==========================================================================
-- Apply via the Supabase SQL Editor or `supabase db push`. Runs idempotently:
-- tables use CREATE TABLE IF NOT EXISTS; policies drop before recreate.
--
-- Identity model
-- --------------
-- Authenticated users live in `auth.users` (managed by Supabase). Rows in
-- the user-scoped tables carry `user_id uuid` referencing `auth.users(id)`
-- with ON DELETE CASCADE. Row-level security is ON for every user-scoped
-- table; the only policy allows `auth.uid() = user_id`.
--
-- Content tables (questions, categories) are shared across all users and
-- are readable by any authenticated user but writable only by the service
-- role (seeding + admin).
-- ==========================================================================

-- Extensions ---------------------------------------------------------------
create extension if not exists "uuid-ossp" with schema extensions;

-- Shared reference content -------------------------------------------------
create table if not exists public.system_design_questions (
  id                           bigint generated by default as identity primary key,
  title                        text not null,
  difficulty                   text default 'Medium',
  description                  text not null,
  hints                        jsonb default '[]'::jsonb,
  constraints                  jsonb default '[]'::jsonb,
  requirements_functional      jsonb default '[]'::jsonb,
  requirements_nonfunctional   jsonb default '[]'::jsonb,
  estimation                   jsonb default '{}'::jsonb,
  api_design                   jsonb default '{}'::jsonb,
  database_schema              jsonb default '{}'::jsonb,
  high_level_design            jsonb default '{}'::jsonb,
  detailed_design              jsonb default '{}'::jsonb,
  trade_offs                   jsonb default '[]'::jsonb,
  tips                         jsonb default '[]'::jsonb,
  thought_process              jsonb default '[]'::jsonb,
  tags                         jsonb default '[]'::jsonb,
  architecture_diagram         jsonb,
  sequence_diagram             text,
  er_diagram                   text,
  thought_flow                 text,
  tradeoff_visual              jsonb,
  senior_topics                jsonb,
  created_at                   timestamptz default now(),
  updated_at                   timestamptz default now()
);

create table if not exists public.coding_questions (
  id               bigint generated by default as identity primary key,
  title            text not null,
  difficulty       text default 'Medium',
  description      text not null,
  hints            jsonb default '[]'::jsonb,
  constraints      jsonb default '[]'::jsonb,
  starter_code     jsonb default '{}'::jsonb,
  boilerplate_code jsonb default '{}'::jsonb,
  test_cases       jsonb default '[]'::jsonb,
  solutions        jsonb default '[]'::jsonb,
  thought_process  jsonb default '[]'::jsonb,
  tips             jsonb default '[]'::jsonb,
  companies        jsonb default '[]'::jsonb,
  topics           jsonb default '[]'::jsonb,
  time_complexity  text default '',
  space_complexity text default '',
  created_at       timestamptz default now(),
  updated_at       timestamptz default now()
);

create table if not exists public.behavioral_categories (
  id          bigint generated by default as identity primary key,
  name        text not null unique,
  description text default '',
  color       text default '#171717',
  icon        text default ''
);

create table if not exists public.behavioral_questions (
  id                          bigint generated by default as identity primary key,
  title                       text not null,
  question_text               text not null,
  category_ids                jsonb default '[]'::jsonb,
  star_guide                  jsonb default '{}'::jsonb,
  sample_response             jsonb default '{}'::jsonb,
  tips                        jsonb default '[]'::jsonb,
  common_pitfalls             jsonb default '[]'::jsonb,
  follow_up_questions         jsonb default '[]'::jsonb,
  what_interviewers_look_for  jsonb default '[]'::jsonb,
  tags                        jsonb default '[]'::jsonb,
  created_at                  timestamptz default now(),
  updated_at                  timestamptz default now()
);

-- User-scoped data ---------------------------------------------------------

-- Optional profile row that augments auth.users with app-specific fields.
-- Auto-inserted via trigger when a new auth.user is created.
create table if not exists public.profiles (
  id         uuid primary key references auth.users(id) on delete cascade,
  name       text,
  target     text default '',
  bio        text default '',
  updated_at timestamptz default now()
);

create table if not exists public.anecdotes (
  id                   bigint generated by default as identity primary key,
  user_id              uuid not null references auth.users(id) on delete cascade,
  title                text not null,
  situation            text default '',
  task                 text default '',
  action               text default '',
  result               text default '',
  category_ids         jsonb default '[]'::jsonb,
  linked_question_ids  jsonb default '[]'::jsonb,
  notes                text default '',
  created_at           timestamptz default now(),
  updated_at           timestamptz default now()
);
create index if not exists anecdotes_user_id_idx on public.anecdotes (user_id);

create table if not exists public.applications (
  id              bigint generated by default as identity primary key,
  user_id         uuid not null references auth.users(id) on delete cascade,
  company         text not null,
  role            text not null,
  status          text default 'Applied',
  applied_date    text default '',
  notes           text default '',
  resume_variant  text default '',
  url             text default '',
  created_at      timestamptz default now(),
  updated_at      timestamptz default now()
);
create index if not exists applications_user_id_idx on public.applications (user_id);

create table if not exists public.interview_rounds (
  id               bigint generated by default as identity primary key,
  user_id          uuid not null references auth.users(id) on delete cascade,
  application_id   bigint references public.applications(id) on delete cascade,
  round_type       text not null,
  date             text default '',
  interviewer      text default '',
  questions_asked  jsonb default '[]'::jsonb,
  notes            text default '',
  result           text default 'Pending',
  created_at       timestamptz default now(),
  updated_at       timestamptz default now()
);
create index if not exists interview_rounds_user_id_idx on public.interview_rounds (user_id);
create index if not exists interview_rounds_app_id_idx on public.interview_rounds (application_id);

-- Practice status per user per question. Replaces the client-side
-- `rounds.practiceStatus.v1` localStorage store.
create table if not exists public.user_progress (
  id             bigint generated by default as identity primary key,
  user_id        uuid not null references auth.users(id) on delete cascade,
  question_type  text not null check (question_type in ('system', 'coding', 'behavioral')),
  question_id    bigint not null,
  status         text default 'todo' check (status in ('todo', 'in-progress', 'mastered')),
  notes          text default '',
  confidence     double precision default 0,
  completed_at   timestamptz,
  updated_at     timestamptz default now(),
  unique (user_id, question_type, question_id)
);
create index if not exists user_progress_user_id_idx on public.user_progress (user_id);

-- Optional: server-synced preferences (theme, accent, density, etc.).
-- For now the app keeps these in localStorage; this table exists so we can
-- sync later without another migration.
create table if not exists public.user_preferences (
  user_id     uuid primary key references auth.users(id) on delete cascade,
  theme       text default 'light',
  accent      text default 'terracotta',
  type_variant text default 'serif-display',
  density     text default 'comfortable',
  nav_style   text default 'sidebar',
  card_treatment text default 'layered',
  updated_at  timestamptz default now()
);

-- Per-user, per-question, per-language code drafts. Synced from the Monaco
-- editor on a 10-second cadence; localStorage is the fast path.
create table if not exists public.code_drafts (
  user_id     uuid not null references auth.users(id) on delete cascade,
  question_id bigint not null,
  language    text not null,
  code        text not null,
  updated_at  timestamptz default now(),
  primary key (user_id, question_id, language)
);

create index if not exists code_drafts_user_id_idx on public.code_drafts (user_id);

-- Trigger: bump updated_at on user-scoped tables ---------------------------
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_anecdotes_updated on public.anecdotes;
create trigger trg_anecdotes_updated
  before update on public.anecdotes
  for each row execute function public.set_updated_at();

drop trigger if exists trg_applications_updated on public.applications;
create trigger trg_applications_updated
  before update on public.applications
  for each row execute function public.set_updated_at();

drop trigger if exists trg_rounds_updated on public.interview_rounds;
create trigger trg_rounds_updated
  before update on public.interview_rounds
  for each row execute function public.set_updated_at();

drop trigger if exists trg_progress_updated on public.user_progress;
create trigger trg_progress_updated
  before update on public.user_progress
  for each row execute function public.set_updated_at();

drop trigger if exists trg_profiles_updated on public.profiles;
create trigger trg_profiles_updated
  before update on public.profiles
  for each row execute function public.set_updated_at();

drop trigger if exists trg_prefs_updated on public.user_preferences;
create trigger trg_prefs_updated
  before update on public.user_preferences
  for each row execute function public.set_updated_at();

drop trigger if exists trg_code_drafts_updated on public.code_drafts;
create trigger trg_code_drafts_updated
  before update on public.code_drafts
  for each row execute function public.set_updated_at();

-- Trigger: auto-create profile + default preferences when a user signs up.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, name)
  values (new.id, coalesce(new.raw_user_meta_data->>'name', split_part(new.email, '@', 1)))
  on conflict (id) do nothing;

  insert into public.user_preferences (user_id) values (new.id)
  on conflict (user_id) do nothing;

  return new;
end;
$$;

drop trigger if exists trg_auth_user_created on auth.users;
create trigger trg_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- Row-Level Security -------------------------------------------------------

-- Shared content: readable by anyone authenticated; writes through service role only.
alter table public.system_design_questions enable row level security;
alter table public.coding_questions        enable row level security;
alter table public.behavioral_categories   enable row level security;
alter table public.behavioral_questions    enable row level security;

drop policy if exists "Content readable by authed users" on public.system_design_questions;
create policy "Content readable by authed users" on public.system_design_questions
  for select to authenticated using (true);

drop policy if exists "Content readable by authed users" on public.coding_questions;
create policy "Content readable by authed users" on public.coding_questions
  for select to authenticated using (true);

drop policy if exists "Content readable by authed users" on public.behavioral_categories;
create policy "Content readable by authed users" on public.behavioral_categories
  for select to authenticated using (true);

drop policy if exists "Content readable by authed users" on public.behavioral_questions;
create policy "Content readable by authed users" on public.behavioral_questions
  for select to authenticated using (true);

-- User-scoped tables: owner-only CRUD.
alter table public.profiles          enable row level security;
alter table public.anecdotes         enable row level security;
alter table public.applications      enable row level security;
alter table public.interview_rounds  enable row level security;
alter table public.user_progress     enable row level security;
alter table public.user_preferences  enable row level security;
alter table public.code_drafts       enable row level security;

drop policy if exists "Profile is self-readable" on public.profiles;
create policy "Profile is self-readable" on public.profiles
  for select using (auth.uid() = id);
drop policy if exists "Profile is self-updatable" on public.profiles;
create policy "Profile is self-updatable" on public.profiles
  for update using (auth.uid() = id);

drop policy if exists "Anecdotes CRUD by owner" on public.anecdotes;
create policy "Anecdotes CRUD by owner" on public.anecdotes
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "Applications CRUD by owner" on public.applications;
create policy "Applications CRUD by owner" on public.applications
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "Rounds CRUD by owner" on public.interview_rounds;
create policy "Rounds CRUD by owner" on public.interview_rounds
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "Progress CRUD by owner" on public.user_progress;
create policy "Progress CRUD by owner" on public.user_progress
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "Preferences CRUD by owner" on public.user_preferences;
create policy "Preferences CRUD by owner" on public.user_preferences
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "Code drafts CRUD by owner" on public.code_drafts;
create policy "Code drafts CRUD by owner" on public.code_drafts
  for all
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);
